[workspace]
members = [
    "radiate",
    "examples/xor-evtree",
    "examples/xor-neat",
    "examples/xor-neat-backprop",
    "examples/lstm-neat",
    "examples/ism",
    "examples/helloworld",
    "web"
]