[workspace]
members = [
    "radiate",
    "radiate_web",
    "examples/xor-neat",
    "examples/xor-neat-backprop",
    "examples/lstm-neat",
    "examples/ism",
    "examples/helloworld",
    "examples/neat-web/neat-server",
    "examples/neat-web/neat-client"
]