[package]
name = "radiate"
version = "1.0.0"
authors = ["pkalivas <peterkalivas@gmail.com>"]
description = "Parallel and customizable genetic programming library"
repository = "https://github.com/pkalivas/radiate"
readme = "../README.md"
categories = ["machine learning", "artificial intelligence", "algorithms", "data science"]
keywords = ["radiate", "genetic", "learning", "artificial", "evolution"]
edition = "2018"
license = "MIT"


[dependencies]
rand="0.7.2"
simple-matrix="0.1.2"
statrs="0.12.0"
rayon="1.2.0"
