[package]
name = "radiate"
version = "1.0.0"
authors = ["pkalivas <peterkalivas@gmail.com>"]
description = "Parallel and customizable genetic programming library"
repository = "https://github.com/pkalivas/radiate"
readme = "../README.md"
categories = ["machine learning", "artificial intelligence", "algorithms", "data science"]
keywords = ["radiate", "genetic", "ml", "ai", "machine", "learning", "artificial", "evolution"]
edition = "2018"


[dependencies]
rand="*"
simple-matrix="*"
statrs="*"
rayon="*"
