[package]
name = "radiate"
version = "1.1.56"
authors = ["pkalivas <peterkalivas@gmail.com>"]
description = "Parallel genetic programming engine capable of evolving solutions for supervised, unsupervised, and general reinforcement learning problems"
repository = "https://github.com/pkalivas/radiate"
readme = "../README.md"
categories = ["science", "simulation", "algorithms", "evolve", "genetic"]
keywords = ["search", "genetic", "learning", "artificial", "evolution"]
edition = "2018"
license = "MIT"


[dependencies]
rand="0.7.2"
rayon="1.2.0"
uuid = { version = "0.8", features = ["serde", "v4"] }
serde = {version ="1.0", features = ["rc"]}
serde_json="1.0.44"
serde_derive="1.0.104"
typetag="0.1"