[package]
name = "radiate"
version = "1.0.5"
authors = ["pkalivas <peterkalivas@gmail.com>"]
description = "Parallel genetic programming engine capable of evolving solutions for supervised, unsupervised, and general reinforcement learning problems"
repository = "https://github.com/pkalivas/radiate"
readme = "../README.md"
categories = ["science", "simulation", "algorithms", "evolve", "genetic"]
keywords = ["search", "genetic", "learning", "artificial", "evolution"]
edition = "2018"
license = "MIT"


[dependencies]
rand="0.7.2"
simple-matrix="0.1.2"
statrs="0.12.0"
rayon="1.2.0"
uuid = { version = "0.8", features = ["v4"] }