[package]
name = "recurrent-neat"
description = "recurrent example for redox using NEAT."
version = "1.0.0"
authors = ["pkalivas <peterkalivas@gmail.com>"]

[dependencies]
radiate={path="../../radiate"}
csv="*"