[package]
name = "neat-server"
description = "XOR for the neat algorithm."
version = "1.0.0"
authors = ["pkalivas <peterkalivas@gmail.com>"]
edition = "2018"


[dependencies]
<<<<<<< HEAD
radiate="{path="../../../radiate}
=======
radiate="1.1.4"
>>>>>>> 8e7836718a5c56d2e2a0646c42b33af5300e3527
radiate_web={path="../../../radiate_web"}
serde = {version ="1.0", features = ["rc"]}
serde_json="1.0.44"
serde_derive="1.0.104"
rocket="0.4.2"


[dependencies.rocket_contrib]
version = "0.4.2"
default-features = false
features = ["tera_templates", "json"]